### ISSUE TITLE
安装好后卡LOGO界面，但是能听到系统引导指示声音

### ISSUE THREAD

**Issue by wssfxtx** [ivan19871002/Thinkpad-P15V-Gen1-Hackintosh#1]
安装好后卡LOGO界面，但是能听到系统引导指示声音，系统已经进入的，就是界面还卡在LOGO

**Comment by ivan19871002** [comment]
你是哪个设备？是我这个设备吗？型号和配置一模一样吗？修改过我的配置了吗？bios 设置说一下。

**Comment by ivan19871002** [comment]
@wssfxtx 我更新了bios 设置项，你参考修改一下试试。

**Comment by wssfxtx** [comment]
我是p15v gen1,10750H+P620+4K显示屏，硬盘是独立安装再一块1T的intel nvme，BIOS按照你的设置改过了

**Comment by ivan19871002** [comment]
> 

看过去应该是 4K 显示的问题。我没有4K的 型号。

**Comment by ivan19871002** [comment]
[https://github.com/ivan19871002/Thinkpad-P15V-Gen1-Hackintosh/blob/main/OC/config_4k.plist](url)

你试试这个配置看看能不能进桌面

**Comment by ivan19871002** [comment]
> 

验证可以了吗？

**Comment by ivan19871002** [comment]
> 我是p15v gen1,10750H+P620+4K显示屏，硬盘是独立安装再一块1T的intel nvme，BIOS按照你的设置改过了

@wssfxtx 新配置验证过了吗？
