### ISSUE TITLE
This disk is locked

### ISSUE THREAD

**Issue by kuyeii** [ivan19871002/Thinkpad-P15V-Gen1-Hackintosh#2]
大佬，按照你给的bios设置完成后准备按照monterey，结果在选择安装磁盘的页面里面没法选择我的磁盘，请问我还需要设置其他的什么地方吗？谢谢大佬
![621651940309_ pic_hd](https://user-images.githubusercontent.com/39783769/167262971-248187a3-4503-4e2d-b0b6-8ee630896fb0.jpg)

**Comment by kuyeii** [comment]
已解决，谢谢大佬提供的efi

**Comment by ivan19871002** [comment]
> 已解决，谢谢大佬提供的efi

可以把解决方案 pull request 给我，或者在这里说明一下。这样可以帮助后来人。

@kuyeii
