### ISSUE TITLE
全屏播放视频一段时间后会黑屏

### ISSUE THREAD

**Issue by kuyeii** [ivan19871002/Thinkpad-P15V-Gen1-Hackintosh#3]
黑屏以后声音还能正常播放，各种控制操作（音量调节等）也都正常，请问这应该怎么办呢？还有笔记本合盖以后再打开也是黑屏，不能正常唤醒

**Comment by ivan19871002** [comment]
> 

盒盖之后，操作一下鼠标 ，键盘 ，应该只是背光没亮而已，能隐约看到 桌面的时候，再次合上盖子 再打开执行唤醒操作，就可以亮了 ，这个已知，我没时间修了

全屏播放这个没遇过 你用的什么播放器 播放的是什么资源
