### ISSUE TITLE
沒有install mac的選項？

### ISSUE THREAD

**Issue by xnastudio** [ivan19871002/Thinkpad-P15V-Gen1-Hackintosh#4]
1. 格式化 Fat32 16G USB
2. 建目录 com.apple.recovery.boot， 里面放BaseSystem.chuynklist 和 BaseSystem。dmg
3. 建目录EFI， 里面放大哥git下载的BOOT 和 OC
4. 用usb启动，但只有 Windows的选项，没有Install mac的选项？？？？
请问哪里做错了，试了很多次，都没有安装的选项？如何解决。

**Comment by ivan19871002** [comment]
我不是这么安装的
我是在pcbeta 下载了 二合一的版本，烧录之后 有一个 efi 分区，把efi扔进去，再正常usb启动就行了。其他方法没试过

**Comment by xnastudio** [comment]
發現按Dortania's OpenCore Install Guide做安裝的USB是不行的。
1.可以用gibMacOS的方法，在Windows下先運行 [BuildmacOSInstallApp.py] ， 下載需要的恢復image， 再運行[MakeInstall.py] 製作USB
2.刪除掉 USB中的EFI 目錄， 替換成別人做好的，同一種機型的EFI
3.用usb開機就可以有Install Mac的選項。

**Comment by xnastudio** [comment]
我以为我解决了，但有出现一个问题，现在在安装Mac OS，找不到本来装Windows的硬盘（Nvme), 大家有什么解决方法？？？

**Comment by ivan19871002** [comment]
> 我以为我解决了，但有出现一个问题，现在在安装Mac OS，找不到本来装Windows的硬盘（Nvme), 大家有什么解决方法？？？
我是单系统。。
