### ISSUE TITLE
睡眠后屏幕背光无法点亮

### ISSUE THREAD

**Issue by tenolztl** [ivan19871002/Thinkpad-P15V-Gen1-Hackintosh#5]
使用你的EFI文件安装系统后，睡眠唤醒时屏幕背光不亮，这个问题你解决了吗？这个问题是电源问题？

**Comment by xnastudio** [comment]
想问一下，你是如何安装的，我现在去到安装的时候，找不到系统本身的硬盘。只看到usb，所以无法继续下去。可以说一下如何制作USB和BIOS如何选择吗？

**Comment by tenolztl** [comment]
我是下载的黑果小兵制作的系统镜像   .dmg 文件，双分区的，使用BalenaEtcher软件直接把 .dmg文件写入到U盘就行了，自动会把U盘分成1个EFI分区和1个放MACOS系统的分区，然后挂载U盘的EFI分区，把下载的EFI文件放置到EFI分区下就行，BIOS按照up主的设置即可。

**Comment by tenolztl** [comment]
> 想问一下，你是如何安装的，我现在去到安装的时候，找不到系统本身的硬盘。只看到usb，所以无法继续下去。可以说一下如何制作USB和BIOS如何选择吗？

安装时从U盘引导，U盘会显示出来install macos的选项

**Comment by tenolztl** [comment]
> 想问一下，你是如何安装的，我现在去到安装的时候，找不到系统本身的硬盘。只看到usb，所以无法继续下去。可以说一下如何制作USB和BIOS如何选择吗？

我使用的是黑锅小兵制作的系统镜像，双分区的，使用balenaetcher软件把.dmg写入U盘即可，会自动有1个EFI分区，1个放MACOS系统的分区，Windows下只能看EFI分区，把EFI文件放到EFI分区下，BIOS安装up主的设置即可，重启从U盘引导就行

**Comment by ivan19871002** [comment]
> 使用你的EFI文件安装系统后，睡眠唤醒时屏幕背光不亮，这个问题你解决了吗？这个问题是电源问题？

目前我这里是概率性的，所以我设置了 00 休眠模式。日常都是 屏保。

黑屏就再合盖再打开 多次尝试

**Comment by tenolztl** [comment]
> > 使用你的EFI文件安装系统后，睡眠唤醒时屏幕背光不亮，这个问题你解决了吗？这个问题是电源问题？
> 
> 目前我这里是概率性的，所以我设置了 00 休眠模式。日常都是 屏保。
> 
> 黑屏就再合盖再打开 多次尝试

我第一次盒盖打开屏幕背光不亮，再次盒盖打开电脑就重启了。。。。

**Comment by ivan19871002** [comment]
> > > 使用你的EFI文件安装系统后，睡眠唤醒时屏幕背光不亮，这个问题你解决了吗？这个问题是电源问题？
> > 
> > 
> > 目前我这里是概率性的，所以我设置了 00 休眠模式。日常都是 屏保。
> > 黑屏就再合盖再打开 多次尝试
> 
> 我第一次盒盖打开屏幕背光不亮，再次盒盖打开电脑就重启了。。。。

我这不是必现的， 而且我也基本不设置 休眠，一直都是屏保，所以就没修。对我来说不是强需求
